export function createWorkspaceStore(recentProjects = []) {
  return {
    workspaces: [],
    recentProjects,
    defaultProjectLocation: "",
    browsedProjectLocation: "",
    createProjectParentPath: "",
    activeWorkspaceId: null,
    nextWorkspaceId: 1,
    notes: [],
    graphIndex: null,
    searchIndex: null,
    byPath: new Map(),
    byKey: new Map(),
    notePaths: new Set(),
    sortedNotes: [],
    sortedParentOptions: [],
    selectedPath: null,
    selectedPaths: new Set(),
    rootPath: "",
    notesPath: "",
    source: "none",
    workspaceName: "",
    dirty: false,
    saveTimer: null,
    saveToken: 0,
    fileSignatures: new Map(),
    liveSyncTimer: 0,
    liveSyncInFlight: false,
    liveSyncToken: 0,
    graphRenderFrame: 0,
    queuedGraphRender: null,
    viewAnimationFrame: 0,
    filter: "",
    searchResults: [],
    searchOpen: false,
    searchActiveIndex: -1,
    validation: [],
    layoutKey: "",
    manualPositions: {},
    autoPositions: new Map(),
    positions: new Map(),
    nodeSizes: new Map(),
    nodeElements: new Map(),
    edgeElements: [],
    edgeElementsByPath: new Map(),
    spatialIndex: null,
    referenceEdges: [],
    referenceEdgeCount: 0,
    largeGraphMode: false,
    labelStats: new Map(),
    labelVisibilityCache: null,
    labelVisibility: null,
    labelVisibilityKey: "",
    labelRefreshFrame: 0,
    hoveredPath: null,
    focusedPath: null,
    editorView: null,
    editorHydrating: false,
    infoHydrating: false,
    graphHasHierarchy: true,
    hierarchyPromptShown: false,
    hierarchyPromptText: "",
    pendingCreatePoint: null,
    nodeClipboard: null,
    ropeElement: null,
    ropeTargetPath: null,
    selectionRectElement: null,
    lastGraphPoint: null,
    lastNodePointerDown: null,
    suppressGraphCreateUntil: 0,
    armedRope: null,
    view: {
      x: 0,
      y: 0,
      scale: 1
    },
    activeInteraction: null,
    interactionFrame: 0,
    queuedInteractionEvent: null,
    graphBounds: null,
    graphViewport: null,
    graphFullscreenFallback: false,
    editorFullscreenFallback: false,
    graphProjectLauncherOpen: false,
    renamingWorkspaceId: null,
    workspaceRenameDraft: "",
    editorPaneWidth: null,
    editorResizeDrag: null,
    appUpdate: null,
    appUpdateCheckTimer: 0,
    appUpdateCheckInFlight: false,
    appUpdateInstallInFlight: false
  };
}
